variables:
  DOCKER_SNAPSHOT_REGISTRY: registry.axwaytest.net
  IMAGE: ${DOCKER_SNAPSHOT_REGISTRY}/jdavanne/mqtt-proxy:$CI_BUILD_REF
  NAME: mqtt-proxy
image: docker:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: golang:latest
  script:
  - make deps-install
  - make build
  tags:
  - shared
test:
  stage: test
  image: tmaier/docker-compose
  before_script:
  - docker info
  script:
  - docker-compose -f docker-compose.test.yml down
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml run sut
  - docker-compose -f docker-compose.test.yml down
  tags:
  - shared
deploy:
  stage: deploy
  before_script:
  - docker info
  script:
  - docker build -t ${IMAGE}-build .
  - docker run --rm ${IMAGE}-build tar cz ${NAME} >${NAME}.tar.gz
  - docker build -t ${IMAGE} -f Dockerfile.small .
  - docker rmi ${IMAGE}-build
  #- docker push ${IMAGE}
  tags:
  - shared
