variables:
  DOCKER_SNAPSHOT_REGISTRY: registry.axwaytest.net
  IMAGE: ${DOCKER_SNAPSHOT_REGISTRY}/jdavanne/mqtt-proxy:$CI_BUILD_REF
  NAME: mqtt-proxy
image: docker:latest
stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: golang:latest
  script:
  - make deps-install
  - make build
  tags:
  - shared
test:
  stage: test
  image: tmaier/docker-compose
  before_script:
  - docker info
  script:
  - docker-compose -f docker-compose.test.yml down
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml --abort-on-container-exit
  after_script:
  - docker-compose -f docker-compose.test.yml down
  tags:
  - shared

