version: "2"

services:
  mqtt-proxy:
    build: .
    environment:
      MQTT_PORT: 1883 # regular mqtt
      MQTT_HOST: 0.0.0.0

      MQTTS_PORT: 1884 # mqtt over tls
      MQTTS_HOST: 0.0.0.0
      MQTTS_CERT: "./certs/server.pem"
      MQTTS_KEY: "./certs/server.key"

      HTTP_PORT: 8080 # mqtt over websocket (and HTTP send API)
      HTTPS_PORT: 8081 # mqtt over tls websocket (and HTTPS send API)
      HTTPS_CERT: "./certs/server.pem"
      HTTPS_KEY: "./certs/server.key"

      MQTT_BROKER_HOST: mosquitto # activemq / rabbitmq / mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_BROKER_USER: guest
      MQTT_BROKER_PASSWORD: guest

      #AUTH_URL: http://policy:3000/mqtt
      AUTH_URL: https://policy:3001/mqtt
      AUTH_CA_FILE: "./certs/policy.pem"
    tty: true
    ports:
      - 1883:1883   # MQTT
      - 1884:1884   # MQTTS
      - 8080:8080   # MQTT on HTTP
      - 8081:8081   # MQTT on HTTPS
    depends_on:
    - policy

  policy:
    build: ./tests/policy
    volumes:
    - ./tests/policy/app.js:/usr/src/app/app.js
    ports:
    - 3000:3000 # to manual test policies ....
    command:
    - node
    - app.js

  rabbitmq:
    build: ./tests/rabbitmq
    ports:
      - 5672        # AMQP
      - 15672:15672 # UI
      - 5883:1883   # MQTT

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 9883:1883   # MQTT
      - 9001:9001
    volumes:
      #- /mosquitto/data
      #- /mosquitto/log
      - ./tests/mosquitto/config:/mosquitto/config

  activemq:
    image: rmohr/activemq:5.14.3-alpine
    ports:
      - 61616:61616 # JMS
      - 8161:8161   # UI
      - 5672        # AMQP  (since `rmohr/activemq:5.12.1`)
      - 61613:61613 # STOMP (since `rmohr/activemq:5.12.1`)
      - 6883:1883   # MQTT  (since `rmohr/activemq:5.12.1`)
      - 61614:61614 # WS    (since `rmohr/activemq:5.12.1`)
    #volumes:
      #- ./activemq/config:/opt/activemq/conf
      #- /var/activemq/data
